// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Healthcare.Model
{

    public partial class DiseaseListItem
    {
        public string name { get; set; }
        public string img { get; set; }
        public string department { get; set; }
        public string place { get; set; }
        public int count { get; set; }
        public int rcount { get; set; }
        public int fcount { get; set; }
        public int id { get; set; }
    }

}
