// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Healthcare.Model
{

    public class DrugShowItem
    {
        public int id { get; set; }
        public string name { get; set; }//名称
        public string img { get; set; }//图片
        public string message { get; set; }//内容
        public int count { get; set; }//访问次数
        public int fcount { get; set; }//收藏数
        public int rcount { get; set; }//评论读数
        public string keywords { get; set; }
        public string description { get; set; }
        public float price { get; set; }//价格
        public string tag { get; set; } //标签
        public string type { get; set; }//类型
    }

}
