// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Healthcare.Model
{

    public class DurgShowItem
    {
        public string name { get; set; }
        public string image { get; set; }
        public int category { get; set; }
        public string message { get; set; }
        public int count { get; set; }
        public int fcount { get; set; }
        public int rcount { get; set; }
        public string ANumber { get; set; }
        public string PType { get; set; }
        public string categoryName { get; set; }
        public string factory { get; set; }
        public int price { get; set; }
        public string tag { get; set; }
        public int id { get; set; }
    }

}
