// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Healthcare.Model
{

    public class GeneralSieveItem
    {
        public string name { get; set; }
        public int id { get; set; }
    }

}
