// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Healthcare.Model
{

    public class NewsShowItem
    {
        public string title { get; set; }
        public string tag { get; set; }
        public string img { get; set; }
        public int count { get; set; }
        public int fcount { get; set; }
        public int rcount { get; set; }
        public string author { get; set; }
        public int focal { get; set; }
        public string md { get; set; }
        public string time { get; set; }
        public int id { get; set; }
    }

}
